# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

############################
# Required Configuration
############################

# Basic Information 
title: Yutaro Ueno
position: Student of Linguistics
affiliation: Department of Linguistics, University of Maryland, College Park<br>Department of Language and Information Sciences, Graduate School of Arts and Sciences, The University of Tokyo (on leave)
affiliation_link: https://linguistics.umd.edu/
email: YOUR_EMAIL_ADDRESS
# address:

# your profile picture
avatar: ./assets/img/profile.jpg

# Sidebar Links 
# For those you don't need, delete or comment out the corresponding line.
cv_link: assets/files/cv.pdf
# arxiv:
# google_scholar:
# math_overflow:
github_link: https://github.com/yueno-ling
linkedin: YOUR_LINKEDIN_URL
# orcid:

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
description: The academic personal homepage of Yutaro Ueno.
keywords: Yutaro Ueno linguistics syntax mathematical linguistics
canonical: https://yueno-ling.github.io/


############################
# Optional Configuration
############################

# Customization
# option to choose between Serif or Sans Serif fonts.
font: "Sans Serif" # "Serif" or "Sans Serif" 

# option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# option to toggle the automatic dark theme
auto_dark_mode: true

# option to make avatar (profile photo) round vs rectangular
round_avatar: false

# option to show thumbnail or "teaser" figure next to each publication
enable_publication_thumbnails: true
enable_notes_thumbnails: false

# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# Google Analytics ID
# Uncomment this if you use Google Analytics
# google_analytics: UA-000000000-0


############################
# Fixed Configuration (ignore this for non-experts)
############################

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-a-github-pages-site-using-jekyll
# remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - html_site/
  - LICENSE
  - README.md
  - minimal-light.gemspec
