# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

############################
# Required Configuration
############################

# Basic Information 
title: Gary Fishman
position: Ph.D. Student
affiliation: National Taiwan University<br>國立台灣大學
affiliation_link: https://www.math.ntu.edu.tw/
email: fishman (at) university.edu
# address: No. 1, Sec. 4, Roosevelt Rd.<br>Taipei City 106, Taiwan (R.O.C.)

# your profile picture
avatar: ./assets/img/profile_alt.jpg

# Sidebar Links 
# For those you don't need, delete or comment out the corresponding line.
cv_link: assets/files/shinchan_sample_cv.pdf
arxiv: https://arxiv.org/a/0000-0002-0101-0521
google_scholar: https://scholar.google.com/citations?user=_D7ce2cAAAAJ&sortby=pubdate
math_overflow: https://mathoverflow.net/users/81295/harry-richman
github_link: https://github.com/harryrichman
# linkedin: https://www.linkedin.com/in/harry-richman/
# orcid: https://orcid.org/0000-0002-0101-0521

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
# description: The academic personal homepage of Gary Fishman.
# keywords: Gary Fishman academic research mathematics
# canonical: https://harryrichman.github.io/minimal-light-academic/


############################
# Optional Configuration
############################

# Customization
# option to choose between Serif or Sans Serif fonts.
font: "Sans Serif" # "Serif" or "Sans Serif" 
# option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true
# option to toggle the automatic dark theme
auto_dark_mode: true
# option to make avatar (profile photo) round vs rectangular
round_avatar: false
# option to show thumbnail or "teaser" figure next to each publication
enable_publication_thumbnails: true
enable_notes_thumbnails: false
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# Google Analytics ID
# Uncomment this if you use Google Analytics
# google_analytics: UA-000000000-0


############################
# Fixed Configuration (ignore this for non-experts)
############################

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
# remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - html_site/
  - LICENSE
  - README.md
  - minimal-light.gemspec
